#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define LOG_CONF_LEVEL_RPL LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_COAP LOG_LEVEL_WARN

#define UIP_CONF_BUFFER_SIZE 256
#define COAP_MAX_CHUNK_SIZE 96
#define QUEUEBUF_CONF_NUM 8

#define ADAPTIVE_SERVER_EP "coap://[fe80::212:7402:2:202]"

#endif
